version: 0.2



phases:
    build:
      commands:
        - echo "Entered into Build Stage..."
        - echo "Building Package"
        - mvn clean package
    post_build:
      commands:
        - echo "Build Stage Completed..."
artifacts:
      files:
        - target/traffic-count-api.jar
      discard-paths: yes