version: 0.2
phases:
    install:
      java: corretto11
    build:
      commands:
        - echo Build started on `date`
        - mvn clean package
artifacts:
      files:
        - appspec.yml
        - traffic-count-api/target/traffic-count-api.war